/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as swipeFiCreditV3Sol from "./SwipeFiCreditV3.sol";
export type { swipeFiCreditV3Sol };
export type { SpendToken } from "./SpendToken";
export type { SwipeFiCreditV2 } from "./SwipeFiCreditV2";
